### PR TITLE
Cordova variable support to override default Android Gradle & iOS Cocoapods dependencies

### PR DESCRIPTION
**Pull request by sagrawal31**
# Breaking Changes

1. Renamed variable `FIREBASE_CORE_VERSION` to `ANDROID_FIREBASE_CORE_VERSION`
2. Renamed variable `FIREBASE_DYNAMIC_LINKS_VERSION` to `ANDROID_ FIREBASE_DYNAMIC_LINKS_VERSION`

### CODE REVIEW

**Comment by chemerisuk** [comment]
Unfortunately cordova preferences don't currently work with `podspec` tags. I tried to extract iOS version in the past but have to [rollback the changes](https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/commit/19623e9c0c9e0325d32ad57950f44aa0add7a6be). More details https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/114 and https://github.com/chemerisuk/cordova-plugin-firebase-messaging/issues/88.

**Comment by sagrawal31** [comment]
Oh! I actually didn't try this after implementing thinking that this will work seamlessly as I have done this for other plugins. Raised an issue here https://github.com/apache/cordova-lib/issues/789

**Comment by sagrawal31** [comment]
@chemerisuk meanwhile Cordova team fixes this issue, can you please merge this PR https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/pull/43 in a temporary branch like `2.x` and release a version like `2.0.5`?

This would be really helpful for others (to us as well) who are using other plugins with 5.x version of Firebase Cocoapods version.

**Comment by chemerisuk** [comment]
@sagrawal31 I can't do that because version 2 starts from -> 6.0.0

If 5.x is needed - just use your fork.

**Comment by sagrawal31** [comment]
Hmmm..thanks for your response @chemerisuk I'll use this fork.

**Pull request closed without merging**
