### PR TITLE
prefixing swizzling logic to avoid conflicts

### PR DESCRIPTION
**Pull request by Athorcis**

### CODE REVIEW

**Comment by isaacsuazo7** [comment]
Hello Atorcis
Conflicts with other plugins that use the method with the same name?
I recently had problems with the Facebook authentication plugin, for some reason the (swizzling) cordova-plugin-firebase-dynamiclinks method (swizzling) was not showing the Facebook login popup in my app.

**Comment by isaacsuazo7** [comment]
Hello Atorcis
Conflicts with other plugins that use the method with the same name?
I recently had problems with the Facebook authentication plugin, for some reason the cordova-plugin-firebase-dynamiclinks method (swizzling) was not showing the Facebook login popup in my app.

**Comment by Athorcis** [comment]
Yes, exactly, some plugins use the exact same name for the replacement method.
It seems that swizzling methods should always be prefixed (https://nshipster.com/method-swizzling/)

**Comment by chemerisuk** [comment]
@Athorcis thanks, I wasn't aware of this. Code will be updated.

**Pull request merged**
