### PR TITLE
fix infinite recursion

### PR DESCRIPTION
**Pull request by lior-frezi**
the current implementation caused an infinite recursion as even if handled was true the recursion continued. this pr fixed the problem for me.

### CODE REVIEW

**Comment by chemerisuk** [comment]
@liorJuice it should not create an infinite recursion.
https://nshipster.com/method-swizzling/
> It may appear that the following code will result in an infinite loop. Surprisingly, it won’t. In the process of swizzling, xxx_viewWillAppear: has been reassigned to the original implementation of UIViewController -viewWillAppear:

**Comment by lior-frezi** [comment]
@chemerisuk but it did create it on my end. as soon as a dynamic link was clicked, my app would open and halt/crash without that fix. in debug i saw endless calls to the same method (the bottom one, the top one i changed because it looked the same, but maybe there is no problem there), with memory going up and up until EXC_BAD_ACCESS  was thrown.

**Comment by KenSoftDev** [comment]
@liorJuice 

Is HTTP GET parameter included in DeepLink?
For example `https://example.com/?id=47`

I also get a similar error.

**Comment by lior-frezi** [comment]
@ken-y2017 the deeplink itself is normal \*\*\*.page.link/\*\*\* but it does lead to an address with query/GET params and even hash(#) on my case.

**Comment by KenSoftDev** [comment]
@liorJuice 

In my case I was able to do the following.

- Do not include GET parameter in deeplink
    - e.g. `https://***.page.link/47`
- Install [two additional libraries](https://ionicframework.com/jp/docs/native/deeplinks)
    - https://www.npmjs.com/package/@ionic-native/deeplinks
    - https://github.com/ionic-team/ionic-plugin-deeplinks

**Comment by chemerisuk** [comment]
This is a bug indeed. I was able to reproduce it locally when there is no other handler for `continueUserActivity`. For `openURL` we don't have this problem because internally cordova has handler for `openURL`. So it looks like current swizzling implementation is buggy.

**Comment by chemerisuk** [comment]
@liorJuice @ken-y2017 
Should be fixed in https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/commit/f83a051119484e7228c6b0fd80b1ebe7d2a0ee14. Can you copy/paste those changes and verify if they fix infinite recursion on your side?

**Comment by lior-frezi** [comment]
@chemerisuk thank you! your new version fixed it!
~please publish a version so i can stop using my repo..~ you already did :D thanks!

**Pull request closed without merging**
